org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
version=4.0.6
group=com.agricraft.agricraft

# Common
minecraft_version=1.20.6
parchment_version=2024.06.16

# NeoForge
neoforge_version=20.6.139

# Fabric
fabric_version=0.100.8+1.20.6
fabric_loader_version=0.15.11

# Mod options
mod_name=AgriCraft
mod_id=agricraft

# Mod deps
modmenu_version=10.0.0
emi_version=1.1.22+1.20.6
jei_version=18.0.0.66
rei_version=15.0.787
jade_fabric_version=5366607
jade_forge_version=5366595
wthit_version=11.4.3
resourcefulconfig_version=2.5.2

enabled_platforms=fabric,neoforge
